---
name: Generate PDF and Add to Repository
on:
  push:
    branches: [main]
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: delay
        run: sleep 10m
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate PDF
        run: python generate_pdf.py
      - name: Commit PDF
        run: |-
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add path/to/generated-pdf.pdf
          git commit -m "Add generated PDF"
          git push
